### PR TITLE
embed wemeet-wayland-screenshare

### LINKED ISSUE #16: The screen sharing function does not support Wayland
The Wayland protocol is the trend, please fully support the Wayland protocol.

### PR DESCRIPTION
**Pull request by ztelliot**
use [wemeet-wayland-screenshare](https://github.com/xuwd1/wemeet-wayland-screenshare) to support screenshare in wayland, fix #16

### CODE REVIEW

**Comment by catsout** [comment]
Does it possible to use freedesktop sdk instead of gnome sdk?

**Comment by ztelliot** [comment]
The `libportal` requires a gtk or qt environment, I'm not sure if there's a way to just use freedesktop sdk.

**Comment by szw0407** [comment]
Personally I guess GNOME SDK is not necessary as the [wemeet-wayland-screenshare](https://github.com/xuwd1/wemeet-wayland-screenshare) project supports more than GNOME and runs well without GNOME. Perhaps I have misunderstood something?

**Comment by JohnNiang** [comment]
Excellent feature! It works very well. How about releasing a new version?

**Comment by ztelliot** [comment]
> Excellent feature! It works very well. How about releasing a new version?

The latest version on flathub already has this feature, so might there's no need to release a version.

**Pull request merged**
